### PR TITLE
Test Cases for Click Task

### PR DESCRIPTION
**Pull request by Siyuan-Deng**
I've added test cases for ClickTask.java. I don't know how to get rid of the previous two commits, please look into the latest rwo commit with description "Added Javadoc for ClickTaskTest.java." and "Wrote test cases for ClickTask.java." for changes.

### CODE REVIEW

**Comment by Siyuan-Deng** [comment]
Oh the first two commits are not showing on GitHub (but it's on IntelliJ), which is nice but also a little bit confusing. TL;DR: GitHub is showing the correct information, ignore the descriptions I wrote.

**Review by tycelm — APPROVED** [review]
very concise tests that cover all the functions, nice work 👍

**Review by kaavyakalani26 — APPROVED** [review]
Looks good Daisy!! Good work with the test cases

**Comment by elenascobici** [comment]
It seems that GitHub classroom is complaining about some of the test cases, make sure you take a look at those!

**Comment by Siyuan-Deng** [comment]
> It seems that GitHub classroom is complaining about some of the test cases, make sure you take a look at those!

I'll take a look, thanks!

**Pull request merged**
